extraScrapeConfigs: |
  - job_name: nOps
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
    - names:
      - nOps-cost-analyzer.nOps.svc
      type: 'A'
      port: 9003
