apiVersion: v1
kind: Service
metadata:
  name: nOps-frontend
  namespace: nOps
  labels:
    app: cost-analyzer
spec:
  type: LoadBalancer
  ports:
    - port: 9090
  selector:
    app: cost-analyzer
